travis:
  secure:
    BINSTAR_TOKEN: RDz6Qzuf6uPkJeJMc1BtomKVuesebYIncCH0rMEIZqWc/CbxibNryR0IDP7+x6P9BUPE2WRKplivl6FoDlihbcfS++t1LaZHf53oLsibId1X1ViaWa669JP06wZIbUVNTV+GVtorvIug7kMka0lwz0j/G4b1clU6RLv+xjUz2obs1wHZeOvFWsgU8SJBPqF5ZHL/g4hbn46W5vHwpQ00q56qsVynsB62WLSDWEY4OqSG3YxZCpwTiTQd7teyhx2mexiUIoocQZ2g14LoQZa4kPTvp5X1xXprem1eed8Lr9T4toB/Se2JIzpwuW+o3iMySfdLhwcgOMf2r6tWdIMXV1dBHg4+LCmvinZbVlwEf+DzbyOBQgDusllOXy9qkrYVzTLY4SzlsfM7gOGUm6tSnQPRu6sEC22oaX0zyDXX5L3fBd27AxZz8wcoDVPUU8CEAnD9St9FxfT3GSe9GMQ1GyqAdih1bJSPVgpxgd1xyJ2JewOBPW+qcX+3zL5tQFHSSMJhb+7PxS/ZdC1Mg/ZkRGuK5jY2dav5Fzbsc9RfrzLvbnrfBvuh6A8X/XLU61jvWgh6R4ew1RGtwL3GOWANjwD5zZWeRqceLOZB0NHuAKbCyjBuRB8SCBkjfRwBIBGG4Jwj7WuyU/wxMVZ8HORmyQ/ZMfF68JuadJsnli6isaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
